/** Search index for the AWGP App Help Center (ids + hrefs; titles from i18n). */
window.AWGP_HELP = {
  categories: [
    { id: 'getting-started', emoji: '👋', href: 'pages/getting-started.html' },
    { id: 'audio', emoji: '🎵', href: 'pages/audio.html' },
    { id: 'rituals', emoji: '🔥', href: 'pages/rituals.html' },
    { id: 'library', emoji: '📚', href: 'pages/library.html' },
    { id: 'events-shaktipeeth', emoji: '📍', href: 'pages/events-shaktipeeth.html' },
    { id: 'daily-thought', emoji: '☀️', href: 'pages/daily-thought.html' },
    { id: 'account-privacy', emoji: '🔐', href: 'pages/account-privacy.html' },
    { id: 'troubleshooting', emoji: '🌩️', href: 'pages/troubleshooting.html' },
    { id: 'faq', emoji: '⭐', href: 'pages/faq.html' },
  ],
  suggested: [
    { id: 'install', href: 'pages/getting-started.html#install' },
    { id: 'playAudio', href: 'pages/audio.html#play-tracks' },
    { id: 'reminders', href: 'pages/daily-thought.html#reminders' },
    { id: 'findCenters', href: 'pages/events-shaktipeeth.html#find-centers' },
    { id: 'audioWontPlay', href: 'pages/troubleshooting.html#audio-wont-play' },
  ],
  articles: [
    { id: 'welcome', categoryId: 'getting-started', href: 'pages/getting-started.html#welcome' },
    { id: 'install', categoryId: 'getting-started', href: 'pages/getting-started.html#install' },
    { id: 'account', categoryId: 'getting-started', href: 'pages/getting-started.html#account' },
    { id: 'navigation', categoryId: 'getting-started', href: 'pages/getting-started.html#navigation' },
    { id: 'requirements', categoryId: 'getting-started', href: 'pages/getting-started.html#requirements' },
    { id: 'playTracks', categoryId: 'audio', href: 'pages/audio.html#play-tracks' },
    { id: 'gayatri', categoryId: 'audio', href: 'pages/audio.html#gayatri' },
    { id: 'playlists', categoryId: 'audio', href: 'pages/audio.html#playlists' },
    { id: 'miniPlayer', categoryId: 'audio', href: 'pages/audio.html#mini-player' },
    { id: 'sharingAudio', categoryId: 'audio', href: 'pages/audio.html#sharing' },
    { id: 'ritualsOverview', categoryId: 'rituals', href: 'pages/rituals.html#overview' },
    { id: 'japa', categoryId: 'rituals', href: 'pages/rituals.html#japa' },
    { id: 'yagya', categoryId: 'rituals', href: 'pages/rituals.html#yagya' },
    { id: 'continueRitual', categoryId: 'rituals', href: 'pages/rituals.html#continue' },
    { id: 'books', categoryId: 'library', href: 'pages/library.html#books' },
    { id: 'magazines', categoryId: 'library', href: 'pages/library.html#magazines' },
    { id: 'audiobooks', categoryId: 'library', href: 'pages/library.html#audiobooks' },
    { id: 'offline', categoryId: 'library', href: 'pages/library.html#offline' },
    { id: 'sharingLibrary', categoryId: 'library', href: 'pages/library.html#sharing' },
    { id: 'findCenters', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#find-centers' },
    { id: 'viewEvents', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#view-events' },
    { id: 'rsvp', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#rsvp' },
    { id: 'shareEvent', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#share-event' },
    { id: 'becomeOrganizer', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#become-organizer' },
    { id: 'createEvent', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#create-event' },
    { id: 'myShaktipeeth', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#my-shaktipeeth' },
    { id: 'review', categoryId: 'events-shaktipeeth', href: 'pages/events-shaktipeeth.html#review' },
    { id: 'dailyThought', categoryId: 'daily-thought', href: 'pages/daily-thought.html#daily-thought' },
    { id: 'reminders', categoryId: 'daily-thought', href: 'pages/daily-thought.html#reminders' },
    { id: 'panchang', categoryId: 'daily-thought', href: 'pages/daily-thought.html#panchang' },
    { id: 'location', categoryId: 'daily-thought', href: 'pages/daily-thought.html#location' },
    { id: 'usingApp', categoryId: 'account-privacy', href: 'pages/account-privacy.html#using-the-app' },
    { id: 'privacy', categoryId: 'account-privacy', href: 'pages/account-privacy.html#privacy' },
    { id: 'crashReports', categoryId: 'account-privacy', href: 'pages/account-privacy.html#crash-reports' },
    { id: 'notifications', categoryId: 'account-privacy', href: 'pages/account-privacy.html#notifications' },
    { id: 'localData', categoryId: 'account-privacy', href: 'pages/account-privacy.html#local-data' },
    { id: 'audioWontPlay', categoryId: 'troubleshooting', href: 'pages/troubleshooting.html#audio-wont-play' },
    { id: 'downloads', categoryId: 'troubleshooting', href: 'pages/troubleshooting.html#downloads' },
    { id: 'notificationsTroubleshoot', categoryId: 'troubleshooting', href: 'pages/troubleshooting.html#notifications' },
    { id: 'signIn', categoryId: 'troubleshooting', href: 'pages/troubleshooting.html#sign-in' },
    { id: 'feedback', categoryId: 'troubleshooting', href: 'pages/troubleshooting.html#feedback' },
    { id: 'faqFree', categoryId: 'faq', href: 'pages/faq.html#free' },
    { id: 'faqAwgpOrg', categoryId: 'faq', href: 'pages/faq.html#awgp-org' },
    { id: 'faqLanguages', categoryId: 'faq', href: 'pages/faq.html#languages' },
    { id: 'faqHostEvents', categoryId: 'faq', href: 'pages/faq.html#host-events' },
    { id: 'faqWatch', categoryId: 'faq', href: 'pages/faq.html#watch' },
    { id: 'faqPlatforms', categoryId: 'faq', href: 'pages/faq.html#platforms' },
    { id: 'faqUpdates', categoryId: 'faq', href: 'pages/faq.html#updates' },
  ],
};
