/** Search index for the AWGP App Help Center. */
window.AWGP_HELP = {
  categories: [
    {
      id: 'getting-started',
      emoji: '👋',
      title: 'Getting Started',
      href: 'pages/getting-started.html',
    },
    {
      id: 'audio',
      emoji: '🎵',
      title: 'Audio & Mantras',
      href: 'pages/audio.html',
    },
    {
      id: 'rituals',
      emoji: '🔥',
      title: 'Rituals & Yagya',
      href: 'pages/rituals.html',
    },
    {
      id: 'library',
      emoji: '📚',
      title: 'Library',
      href: 'pages/library.html',
    },
    {
      id: 'daily-thought',
      emoji: '☀️',
      title: 'Daily Thought & Panchang',
      href: 'pages/daily-thought.html',
    },
    {
      id: 'account-privacy',
      emoji: '🔐',
      title: 'Account & Privacy',
      href: 'pages/account-privacy.html',
    },
    {
      id: 'troubleshooting',
      emoji: '🌩️',
      title: 'Troubleshooting',
      href: 'pages/troubleshooting.html',
    },
    {
      id: 'faq',
      emoji: '⭐',
      title: 'FAQ',
      href: 'pages/faq.html',
    },
  ],
  suggested: [
  {
    title: 'Install AWGP App on iOS or Android',
    href: 'pages/getting-started.html#install',
  },
  {
    title: 'Play Pragya Geet, bhajans, and mantras',
    href: 'pages/audio.html#play-tracks',
  },
  {
    title: 'Set up Daily Thought reminders',
    href: 'pages/daily-thought.html#reminders',
  },
  {
    title: 'Audio not playing — what to try',
    href: 'pages/troubleshooting.html#audio-wont-play',
  },
  ],
  articles: [
    { title: 'Welcome to AWGP App', category: 'Getting Started', href: 'pages/getting-started.html#welcome' },
    { title: 'Install on iOS & Android', category: 'Getting Started', href: 'pages/getting-started.html#install' },
    { title: 'No account needed', category: 'Getting Started', href: 'pages/getting-started.html#account' },
    { title: 'Navigating the app', category: 'Getting Started', href: 'pages/getting-started.html#navigation' },
    { title: 'System requirements', category: 'Getting Started', href: 'pages/getting-started.html#requirements' },
    { title: 'Playing audio tracks', category: 'Audio & Mantras', href: 'pages/audio.html#play-tracks' },
    { title: 'Gayatri Mantra & aarti', category: 'Audio & Mantras', href: 'pages/audio.html#gayatri' },
    { title: 'Playlists (private & public)', category: 'Audio & Mantras', href: 'pages/audio.html#playlists' },
    { title: 'Mini player & CarPlay', category: 'Audio & Mantras', href: 'pages/audio.html#mini-player' },
    { title: 'Sharing audio', category: 'Audio & Mantras', href: 'pages/audio.html#sharing' },
    { title: 'Rituals overview', category: 'Rituals & Yagya', href: 'pages/rituals.html#overview' },
    { title: 'Gayatri Japa counter', category: 'Rituals & Yagya', href: 'pages/rituals.html#japa' },
    { title: 'Yagya practices', category: 'Rituals & Yagya', href: 'pages/rituals.html#yagya' },
    { title: 'Continue where you left off', category: 'Rituals & Yagya', href: 'pages/rituals.html#continue' },
    { title: 'Books & EPUB reader', category: 'Library', href: 'pages/library.html#books' },
    { title: 'Magazines & Akhandjyoti', category: 'Library', href: 'pages/library.html#magazines' },
    { title: 'Audiobooks & podcasts', category: 'Library', href: 'pages/library.html#audiobooks' },
    { title: 'Reading lists & offline', category: 'Library', href: 'pages/library.html#offline' },
    { title: 'Share a book or magazine link', category: 'Library', href: 'pages/library.html#sharing' },
    { title: 'Daily Thought', category: 'Daily Thought & Panchang', href: 'pages/daily-thought.html#daily-thought' },
    { title: 'Daily Thought reminders', category: 'Daily Thought & Panchang', href: 'pages/daily-thought.html#reminders' },
    { title: 'Panchang on Home', category: 'Daily Thought & Panchang', href: 'pages/daily-thought.html#panchang' },
    { title: 'My location for Panchang', category: 'Daily Thought & Panchang', href: 'pages/daily-thought.html#location' },
    { title: 'Using AWGP App today', category: 'Account & Privacy', href: 'pages/account-privacy.html#using-the-app' },
    { title: 'Privacy & your data', category: 'Account & Privacy', href: 'pages/account-privacy.html#privacy' },
    { title: 'Anonymous crash reports', category: 'Account & Privacy', href: 'pages/account-privacy.html#crash-reports' },
    { title: 'Notification settings', category: 'Account & Privacy', href: 'pages/account-privacy.html#notifications' },
    { title: 'Clear local data', category: 'Account & Privacy', href: 'pages/account-privacy.html#local-data' },
    { title: 'Audio won\'t play', category: 'Troubleshooting', href: 'pages/troubleshooting.html#audio-wont-play' },
    { title: 'Downloads & storage', category: 'Troubleshooting', href: 'pages/troubleshooting.html#downloads' },
    { title: 'Notifications not arriving', category: 'Troubleshooting', href: 'pages/troubleshooting.html#notifications' },
    { title: 'Account registration (not available yet)', category: 'Troubleshooting', href: 'pages/troubleshooting.html#sign-in' },
    { title: 'Send feedback or report a bug', category: 'Troubleshooting', href: 'pages/troubleshooting.html#feedback' },
    { title: 'Is AWGP App free?', category: 'FAQ', href: 'pages/faq.html#free' },
    { title: 'Relationship to awgp.org', category: 'FAQ', href: 'pages/faq.html#awgp-org' },
    { title: 'Languages & content', category: 'FAQ', href: 'pages/faq.html#languages' },
    { title: 'Apple Watch companion', category: 'FAQ', href: 'pages/faq.html#watch' },
    { title: 'Android vs iOS features', category: 'FAQ', href: 'pages/faq.html#platforms' },
    { title: 'How to update the app', category: 'FAQ', href: 'pages/faq.html#updates' },
  ],
};
